# Generated by Django 3.2.5 on 2021-08-02 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='debit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbt', models.CharField(max_length=30)),
                ('dbt_amount', models.IntegerField()),
                ('journal_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.my_journal')),
            ],
        ),
        migrations.CreateModel(
            name='credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdt', models.CharField(max_length=30)),
                ('cdt_amount', models.IntegerField()),
                ('contra_trans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.debit')),
            ],
        ),
    ]
