# Generated by Django 3.2.5 on 2021-07-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='debit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbt', models.CharField(max_length=10)),
                ('dbt_amount', models.IntegerField()),
                ('cdt', models.CharField(max_length=10)),
                ('cdt_amount', models.IntegerField(verbose_name=models.IntegerField())),
            ],
        ),
    ]
