# Generated by Django 3.2.5 on 2021-07-31 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debit',
            name='cdt',
        ),
        migrations.RemoveField(
            model_name='debit',
            name='cdt_amount',
        ),
        migrations.CreateModel(
            name='credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdt', models.CharField(max_length=10)),
                ('cdt_amount', models.IntegerField()),
                ('contra_trans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.debit')),
            ],
        ),
    ]
