# Generated by Django 3.2.5 on 2021-08-06 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.IntegerField(default=0)),
                ('cr', models.IntegerField(default=0)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.transaction')),
            ],
        ),
    ]
